services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles
    depends_on:
      - app

  app:
    image: ${IMAGE}
    environment:
      - ALLOWED_HOSTS=*
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - staticfiles:/app/staticfiles

  postgres:
    image: postgres:14.7
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres:
  staticfiles:
