services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles
    depends_on:
      - app

  app:
    image: ${IMAGE}
    environment:
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://devpro-rest:mysecretpassword@postgres:5432/devpro-rest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - staticfiles:/app/staticfiles

  postgres:
    image: postgres:14.7
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: devpro-rest

volumes:
  postgres:
  staticfiles:
