name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - deploy-workflow

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login do container registry
        run: doctl registry login

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/walison-devpro/devpro/rest-na-pratica:${{ github.sha }}